version: 2

jobs:
  test:
    docker:
      - image: cimg/go:1.14
      - image: circleci/redis:4-alpine
    steps:
      - checkout
      - run: make test-ci
      - run:
          name: Upload coverage
          command: |
            go get github.com/mattn/goveralls
            goveralls -coverprofile=coverage.out -service=circle-ci -repotoken $COVERALLS_TOKEN

workflows:
  version: 2
  ci:
    jobs:
      - test
