version: 2

jobs:
  test:
    docker:
      - image: cimg/go:1.14
      - image: circleci/redis:4-alpine
    steps:
      - checkout
      - run: make test-ci

workflows:
  version: 2
  ci:
    jobs:
      - test
